### ISSUE TITLE
Future esphome (custom?) component?

### ISSUE THREAD

**Issue by SkateWarp** [htmltiger/tcl-electriq-split-ac#2]
First of all, thank you for your work and dedication with this! 😄 
Do you plan to do a ESPHome component of it?

**Comment by htmltiger** [comment]
I am not using ESPHome build system unable to test it but the code can be ported onto this.
https://github.com/dslatford/electriq_ac

yaml config should be
```
uart:
  id: uart_bus
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600
  parity: EVEN
```

need to alter heartbeat, checksum, bits position and should work
